Repository oasis-open/cti-python-stix2, pull requests merged in 2018-06, with the labels that each got.

#190 Cannot execute sample code.
  README.rst
Labels: documentation

#192 Revamp code related to "pretty" JSON serialization
  stix2/base.py
  stix2/test/test_utils.py
  stix2/utils.py
Labels: enhancement

#199 Update base.py
  stix2/base.py
Labels: bug
